# Generated by Django 6.0.2 on 2026-03-02 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forklift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка погрузчика')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер погрузчика')),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Грузоподъемность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Время и дата изменения')),
                ('updated_by', models.CharField(max_length=255, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Погрузчик',
                'verbose_name_plural': 'Погрузчики',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Дата и время установления проблемы')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время решения проблемы')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('forklift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='registry.forklift', verbose_name='Погрузчик')),
            ],
            options={
                'verbose_name': 'Простой',
                'verbose_name_plural': 'Простои',
                'ordering': ('-started_at',),
            },
        ),
    ]
